### ISSUE TITLE
Request for Experimental Details

### ISSUE THREAD

**Issue by Jiany-Zhang** [BatsResearch/ex2#1]
Hi!
Thanks for this brilliant work! Could you provide more training details like the batch size and how many GPUs are used for training? I can't find these information in the code and paper. Thanks for your kind help!

**Comment by Reza-esfandiarpoor** [comment]
Hi,

The parameters that we use are set as default in the code.
We run all our experiments on a single GPU with at least 48GB of memory.

**Comment by Jiany-Zhang** [comment]
Many thanks for your help!
